### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by evonreis**
Checklist
* [ x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Rerenders the feestock.  This is an attempt to get a new build that depends on a newer version of xorg-libx11.

### CODE REVIEW

**Comment by pkgw** [comment]
This looks good, but for posterity, can you please write a couple of sentences about the motivation for the rerender here?

**Comment by evonreis** [comment]
LIGO is updating a single conda environment that depends on the latest version of the "root_base" package.  

"root_base" has moved on to newer version of xorg-libx11.  This is causing conflicts with a number of other packages in the environment that are built against older versions, including "xorg-libxp".   In every case so far, a re-render of the other packages has been enough to get a compatible build.

**Comment by evonreis** [comment]
To be clear, the only manual change I made was to the build number.  All other changes are from the re-render.

**Comment by pkgw** [comment]
Great, thanks for explaining!

**Pull request merged**
